config/routes.rb
  Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'login' => 'authentications#new'
  post 'login' => 'authentications#create'
  delete 'login' => 'authentications#destroy'
  
  resources :students
  resources :teachers
  resources :courses 
  resources :course_loads
  resources :course_rosters
  resources :attendances
  resources :sessions
 end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

  belongs_to :session
  belongs_to :student
  
  validates(:present, presence: true)
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_loads
  has_many :course_rosters
  has_many :teachers, :through => :course_loads
  has_many :students, :through => :course_rosters
  has_many :sessions

  validates(:name, presence: true, length: {maximum: 50}, uniqueness: true)
end

app/models/course_load.rb
class CourseLoad < ActiveRecord::Base
  belongs_to :course
  belongs_to :teacher
end

app/models/course_roster.rb
class CourseRoster < ActiveRecord::Base
  belongs_to :course
  belongs_to :student
end

app/models/session.rb
class Session < ActiveRecord::Base

  belongs_to :course
  has_many :attendances

  validates(:date, presence: true)
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :course_rosters
  has_many :courses, :through => :course_rosters 
  has_many :attendances

  validates(:name, presence: true, length: {maximum: 50}, uniqueness: true)

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :course_loads
  has_many :courses, :through => :course_loads
  has_secure_password

  validates(:name, presence: true, length: {maximum: 50}, uniqueness: true)

  VALID_PASSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$\z/
  validates(:password, presence: true, length: {maximum: 10}, format: { with: VALID_PASSWORD_REGEX})

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX })  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def index
    @attendances = Attendance.all
  end

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)

    if @attendance.save
      redirect_to attendances_path
    else
      render(:new)
    end
  end

  def attendance_params
    params.require( :attendance).permit(:session_id, :student_id, :present)
  end

  def show
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path
    else
      render(:new)
    end
  end

  def course_params
    params.require( :course).permit( :name)
  end

  def edit
    @course = Course.find(params[:id])
  end

  # DELETE /course/1
  # DELETE /course/1.json
  def destroy
    Course.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to course_url, notice: 'Course was successfully removed.' }
      format.json { head :no_content }
    end
    # redirect_to static_pages_home_path
  end

# This should not be here, index action is used instead. Remember to delete it and check the routes.
  def show
    @courses = Course.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
   @sessions = Session.all
  end

  def show
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(sessions_params)

    if @session.save
      redirect_to sessions_path
    else
      render(:new)
    end
  end

  def destroy
  end

  private
  def sessions_params
    params.require(:session).permit(:date, :course_id, :attendance_id )
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  def index
    @students = Student.all  
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    @student.save
    redirect_to @student
  end

  def student_params
    params.require( :student).permit( :name)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all  
  end

  def edit
    # Edit will delete the old data and replace with new
    @student = Student.find(params[:id])
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path
    else
      render(:new)
    end
  end

  def student_params
    params.require( :student).permit( :name)
  end

 # DELETE /student/1
  # DELETE /student/1.json
  def destroy
    Student.find(params[:id]).destroy
  #  respond_to do |format|
  #    format.html { redirect_to student_url, notice: 'Student was successfully removed.' }
  #    format.json { head :no_content }
  #  end
    redirect_to students_path
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to teachers_path
    else
      render(:new)
    end
  end

  def teacher_params
    params.require( :teacher).permit( :name, :email, :password, :password_confirmation)
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  # DELETE /teacher/1
  # DELETE /teacher/1.json
  def destroy
    Teacher.find(params[:id]).destroy
  #  respond_to do |format|
  #    format.html { redirect_to teacher_url, notice: 'Student was successfully removed.' }
  #    format.json { head :no_content }
  #  end
    redirect_to static_pages_home_path
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/course_load_helper.rb
module CourseLoadHelper
end

app/helpers/course_roster_helper.rb
module CourseRosterHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/destroy.html.erb
<% provide(:title, "Destroy") %>
<% provide(:intro, "") %>
<p>Are you sure you want to delete <%= student(params :name) %>?</p>

app/views/students/edit.html.erb
<% provide(:title, "Edit Student") %>
<% provide(:intro, "This page will allow the user/teacher to edit or update the data for a student. Right now that is only one string field for name. ") %>

<p><%= render 'form' %>
   <%= link_to 'Back', students_path %>
</p>
<p>Updated by Mlworle on <%= Time.zone.now %></p>

app/views/students/index.html.erb
<%= provide(:title, "Student Index") %>
<%= provide(:intro, "Teacher can choose to create a new student, update an existing one or delete a student from the list.") %>
<ul>
  <li>Student</li>
    <ol>
    <% @students.each do |student|  %>
    <li> <%= student.name  %></li>
     <%= link_to 'Edit', edit_student_path(student)  %>
     <%= link_to 'Delete', student, method: :delete, data: {confirm: 'Are you sure?'}  %>
     <%= link_to 'Courses', course_rosters_path %>
    <% end  %>
  </ol>
</ul>
<br>
<h2><p>Want to create a new student? Click here: <%= link_to 'New', new_student_path  %></h2>

app/views/students/new.html.erb
<% provide(:title, "New Student") %>
<% provide(:intro, "This page will allow the user/teacher to input the data for a new student. Right now that is only one string field for name. Access to the database needs to be established.") %>

<p><%= render 'form' %>
   <%= link_to 'Back', students_path %>
</p>

<p>Updated by Mlworle on <%= Time.zone.now  %></p>

app/views/students/show.html.erb
<% provide(:title, "Show Students") %>
<% provide(:intro, "Under construction.") %>