config/routes.rb
  Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'login' => 'authentications#new'
  post 'login' => 'authentications#create'
  delete 'login' => 'authentications#destroy'
  
  resources :students
  resources :teachers
  resources :courses 
  resources :course_loads
  resources :course_rosters
  resources :attendances
  resources :sessions
 end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

  belongs_to :session
  belongs_to :student
  
  validates(:present, presence: true)
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_loads
  has_many :course_rosters
  has_many :teachers, :through => :course_loads
  has_many :students, :through => :course_rosters
  has_many :sessions

  validates(:name, presence: true, length: {maximum: 50}, uniqueness: true)
end

app/models/course_load.rb
class CourseLoad < ActiveRecord::Base
  belongs_to :course
  belongs_to :teacher
end

app/models/course_roster.rb
class CourseRoster < ActiveRecord::Base
  belongs_to :course
  belongs_to :student
end

app/models/session.rb
class Session < ActiveRecord::Base

  belongs_to :course
  has_many :attendances

  validates(:date, presence: true)
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :course_rosters
  has_many :courses, :through => :course_rosters 
  has_many :attendances

  validates(:name, presence: true, length: {maximum: 50}, uniqueness: true)

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :course_loads
  has_many :courses, :through => :course_loads
  has_secure_password

  validates(:name, presence: true, length: {maximum: 50}, uniqueness: true)

  VALID_PASSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$\z/
  validates(:password, presence: true, length: {maximum: 10}, format: { with: VALID_PASSWORD_REGEX})

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX })  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path
    else
      render(:new)
    end
  end

  def course_params
    params.require( :course).permit( :name)
  end

  def edit
    @course = Course.find(params[:id])
  end

  # DELETE /course/1
  # DELETE /course/1.json
  def destroy
    Course.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to course_url, notice: 'Course was successfully removed.' }
      format.json { head :no_content }
    end
    # redirect_to static_pages_home_path
  end

# This should not be here, index action is used instead. Remember to delete it and check the routes.
  def show
    @courses = Course.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
   @sessions = Session.all
  end

  def show
  end

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(sessions_params)

    if @session.save
      redirect_to sessions_path
    else
      render(:new)
    end
  end

  def destroy
  end

  private
  def sessions_params
    params.require(:session).permit(:date, :course_id, :attendance_id )
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  def index
    @students = Student.all  
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    @student.save
    redirect_to @student
  end

  def student_params
    params.require( :student).permit( :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/course_load_helper.rb
module CourseLoadHelper
end

app/helpers/course_roster_helper.rb
module CourseRosterHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Attinderance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<div id="header">Attinderance | <%= yield(:title) %>
		<div class="outer_container">
			<div class="container">Create New
				<ul><li><%= link_to 'Teacher', new_teacher_path %></li>
					<li><%= link_to 'Student', new_student_path %></li>
					<li><%= link_to 'Course', new_course_path %></li>
				</ul>
			</div>
			<div class="container">Take Attendance
				<ul><li><%= link_to 'Session', new_session_path %></li>
					<li><%= link_to 'Attendance',new_attendance_path %></li>
					
				</ul>
			</div>
			<div class="container">Navigate
				<ul><li><%= link_to 'Home', static_pages_home_path %></li>
					<li><%= link_to 'Course Roster', course_rosters_path %></li>
					<li><%= link_to 'Course Loads', course_loads_path %></li>
					<li><%= link_to 'About', static_pages_about_path %></li>
					<li><%= link_to 'Help', static_pages_help_path %></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="intro">
		<%= yield(:intro) %>
	</div>
	<div class = "site_map">
	    <p>Updated by Mlworle on <%= Time.zone.now %></p>
    </div>
    <%= yield %>
</body>
</html>